# Generated by Django 2.2.1 on 2019-12-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulomanufacturadodetalle',
            old_name='ArticuloManufacturado',
            new_name='articuloManufacturado',
        ),
        migrations.RemoveField(
            model_name='articulomanufacturado',
            name='tiempoEstiimadoCocina',
        ),
        migrations.AddField(
            model_name='articulomanufacturado',
            name='tiempoEstimadoCocina',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='esInsumo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precioCompra',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precioVenta',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stockActual',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='unidadDeMedida',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articulomanufacturado',
            name='denominacion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articulomanufacturado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='articulomanufacturado',
            name='precioVenta',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='articulomanufacturadodetalle',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='articulomanufacturadodetalle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='rubroarticulo',
            name='denominacion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rubroarticulo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
