# Generated by Django 2.2.1 on 2019-12-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0002_auto_20191223_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='unidadDeMedida',
            field=models.CharField(max_length=40),
        ),
    ]
