# Generated by Django 2.2.1 on 2020-01-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0005_auto_20200107_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='precioCompra',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='precioVenta',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='stockActual',
        ),
        migrations.RemoveField(
            model_name='articulomanufacturado',
            name='precioVenta',
        ),
        migrations.RemoveField(
            model_name='articulomanufacturado',
            name='tiempoEstimadoCocina',
        ),
        migrations.RemoveField(
            model_name='articulomanufacturadodetalle',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='subtotal',
        ),
    ]
